name: easy_mask
version: 1.0.2

description: Easy Mask for TextField using only a String as parameter. It controls user's cursor.
homepage: https://github.com/danilocoppi/flutter-textfield-mask

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


