name: easy_mask
version: 1.1.0

description: Easy and Powerful Mask for TextField using only a String as parameter. Has multi mask support, reverse mask for currency and placeholder. It controls user's cursor.
homepage: https://github.com/danilocoppi/flutter-textfield-mask

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


